---
title: Explore Anders Ekholm's SelectionShare & TimingShare
author: Timely Portfolio
github: {user: timelyportfolio, repo: rCharts_factor_analytics, branch: "gh-pages"}
framework: bootplus
layout: post
mode: selfcontained
highlighter: prettify
hitheme: twitter-bootstrap
lead : >
  Simple Example in R
assets:
  js:
    - "http://d3js.org/d3.v3.min.js"
    - "http://dimplejs.org/dist/dimple.v2.0.0.min.js"
    - "http://timelyportfolio.github.io/rCharts_dimple/js/d3-grid.js"
  css:
    - "http://fonts.googleapis.com/css?family=Raleway:300"
    - "http://fonts.googleapis.com/css?family=Oxygen"    
---

# [SelectionShare and TimingShare](http://ssrn.com/abstract=2463649)

<style>
body{
  font-family: 'Oxygen', sans-serif;
  font-size: 15px;
  line-height: 22px;
}

h1,h2,h3,h4 {
  font-family: 'Raleway', sans-serif;
}

</style>


```{r echo = F, warning=F, error=F, message=F, cache=F}
#require(knitr)
knitr::opts_chunk$set(warning=F, error=F, message=F, fig.width = 10, fig.height = 6, results='asis', cache = F, tidy = F)
options(rcharts.mode="inline")
```

---
# Depend on Other R Packages

```{r "libraries"}
# perform Ekholm (2012,2014) analysis on mutual fund return data

# Ekholm, A.G., 2012
# Portfolio returns and manager activity:
#    How to decompose tracking error into security selection and market timing
# Journal of Empirical Finance, Volume 19, pp 349-€“358

# Ekholm, Anders G., July 21, 2014
# Components of Portfolio Variance:
#    R2, SelectionShare and TimingShare
# Available at SSRN: http://ssrn.com/abstract=2463649

require(quantmod)
require(PerformanceAnalytics)
# love me some pipes; will happily translate if pipes aren't you're thing
# devtools::install_github("renkun_ken/pipeR")
require(pipeR) 
```

---
# Ugly Way to Get Kenneth French Factor Data

```{r "french factors"}
#daily factors from Kenneth French Data Library
#get Mkt.RF, SMB, HML, and RF
#UMD is in a different file
my.url="http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_daily.zip"
my.tempfile<-paste(tempdir(),"\\frenchfactors.zip",sep="")
my.usefile<-paste(tempdir(),"\\F-F_Research_Data_Factors_daily.txt",sep="")
download.file(my.url, my.tempfile, method="auto", 
              quiet = FALSE, mode = "wb",cacheOK = TRUE)
unzip(my.tempfile,exdir=tempdir(),junkpath=TRUE)
#read space delimited text file extracted from zip
french_factors <- read.table(file=my.usefile,
                             header = TRUE, sep = "",
                             as.is = TRUE,
                             skip = 4, nrows=23257)
#get xts for analysis
french_factors_xts <- as.xts(
  french_factors,
  order.by=as.Date(
    rownames(french_factors),
    format="%Y%m%d"
  )
)

#now get the momentum factor
my.url="http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Momentum_Factor_daily.zip"
my.usefile<-paste(tempdir(),"\\F-F_Momentum_Factor_daily.txt",sep="")
download.file(my.url, my.tempfile, method="auto", 
              quiet = FALSE, mode = "wb",cacheOK = TRUE)
unzip(my.tempfile,exdir=tempdir(),junkpath=TRUE)
#read space delimited text file extracted from zip
french_momentum <- read.table(file=my.usefile,
                              header = TRUE, sep = "",
                              as.is = TRUE,
                              skip = 13, nrows=23156)
#get xts for analysis
french_momentum_xts <- as.xts(
  french_momentum,
  order.by=as.Date(
    rownames(french_momentum),
    format="%Y%m%d"
  )
)

#merge UMD (momentum) with other french factors
french_factors_xts %>>%
  merge( french_momentum_xts )  %>>%
  na.omit %>>%
  ( .[] / 100 ) -> french_factors_xts
```

---
# Get  Price / Return Data from Yahoo! Finance

```{r "mutualfund_data"}
#get a fund to analyze
# will use Vulcan Value the biggest mutual fund in Birmingham, Alabama
ticker <- 'VVPLX'
ticker %>>% 
  getSymbols( from="1896-01-01", adjust=TRUE, auto.assign=F ) %>>%
  ( .[,4] ) %>>%
  ROC( type = "discrete", n = 1 ) %>>%
  merge ( french_factors_xts ) %>>%
  na.omit -> perfComp

colnames(perfComp)[1] <- gsub( ".Close", "", colnames(perfComp)[1] )
```


---
# Calculate Ekholm's SelectionShare and TimingShare

```{r "ekholm"}
# do it with lots of comments and no pipes
# to clarify the steps

# 1.  Linear Regression of Fund Return vs (Market - RiskFree)
#      which gives us the well-known Jensen alpha and beta
jensenLM <- lm( data = perfComp, VVPLX ~ Mkt.RF )

# 2.  Run another linear regression on the residuals ^2
#       vs the (Mkt - Rf)^2
residuals.df <- data.frame(
  residuals = as.numeric( residuals( jensenLM ) ) ^ 2
  , Mkt.RF_sq = as.numeric( perfComp$Mkt.RF ^ 2 )
)
residualsLM <- lm(
  data = residuals.df
  , residuals.df$residuals ~ residuals.df$Mkt.RF_sq
)

# 3. Get ActiveAlpha and ActiveBeta from coefficients
#     see
# Ekholm, A.G., 2012
# Portfolio returns and manager activity:
#    How to decompose tracking error into security selection and market timing
# Journal of Empirical Finance, Volume 19, pp 349-€“358
activeAlpha = coefficients( residualsLM )[1] ^ (1/2)
activeBeta = coefficients( residualsLM )[2] ^ (1/2)

# 4. Last step to calculate SelectionShare and TimingShare
selectionShare = activeAlpha ^ 2 /
                    (
                      var( perfComp$VVPLX ) *
                      (nrow( perfComp ) - 1) / nrow( perfComp )
                    )

timingShare = activeBeta ^ 2 *
                mean( residuals.df$Mkt.RF_sq ) /
                (
                  var( perfComp$VVPLX ) *
                    ( nrow( perfComp ) - 1) / nrow( perfComp )
                )

# check our work r^2  + selectionShare + timingShare should equal 1
summary(jensenLM)$"r.squared" + selectionShare + timingShare
```

---
# One-line It with Function

```{r "ekholm_function"}
jensen_ekholm <- function( data, ticker = NULL ){
  
  if(is.null(ticker)) ticker <- colnames(data)[1]
  
  as.formula ( paste0(ticker, " ~  Mkt.RF" ) ) %>>%
    ( lm( data = data, . ) -> jensenLM )
  
  jensenLM %>>%
    residuals %>>%
    (. ^ 2 ) %>>%
    (
      data.frame(
        data
        , "fitted_sq" = .
        , lapply(data[,2],function(x){
          structure(
            data.frame( as.numeric(x) ^ 2 )
            , names = paste0(names(x),"_sq")
          ) %>>%
            return
        }) %>>% ( do.call( cbind, . ) )
      ) -> return_data_jensen
    )
  
  return_data_jensen %>>%
    ( lm( fitted_sq ~ Mkt.RF_sq, data = . ) )%>>%
    coefficients %>>%
    ( . ^ (1/2) ) %>>%
    t %>>%
    (
      structure(
        data.frame(.),
        names = c("ActiveAlpha", paste0("ActiveBeta_",colnames(.)[-1]))
      )
    ) %>>% 
    (
      data.frame(
        .
        , "SelectionShare" = .$ActiveAlpha ^ 2 / (var(return_data_jensen[,ticker]) * (nrow(return_data_jensen) - 1) / nrow(return_data_jensen))
        , "TimingShare" = .$ActiveBeta_Mkt.RF_sq ^ 2* mean( return_data_jensen$Mkt.RF_sq ) / (var(return_data_jensen[,ticker]) * (nrow(return_data_jensen) - 1) / nrow(return_data_jensen))
        
      )
    ) %>>%
    (
      list( "ekholm" = ., "linmod" = jensenLM )
    ) %>>%
    return
}

jensen_ekholm( perfComp ) -> jE

jE %>>% ( summary(.$linmod)$"r.squared" + jE$ekholm[1,3] + jE$ekholm[1,4] )
```